Repository hashicorp/nomad-pack, pull requests merged in 2023-08, with the labels that each got.

#394 [dep] Update to golang.org/x/exp v0.0.0-20230728194245
  go.mod
  go.sum
Labels: chore, dependencies

#398 [chore] update to go 1.20.7
  .go-version
Labels: theme/building, chore

#399 [deps] nomad co-dependency updates
  go.mod
  go.sum
Labels: chore, dependencies, theme/dependencies

#400 [chore] bump golang.org/x/net v0.12.0 -> v0.13.0
  go.mod
  go.sum
Labels: theme/dependency, theme/security, chore, dependencies

#402 [chore] use hashicorp/setup-golang action
  .github/workflows/go-tests.yml
  .github/workflows/golang-ci-lint.yml
Labels: chore, theme/gh/actions

#404 [tests] Update cache tests
  fixtures/test_registry/packs/simple_docker/CHANGELOG.md
  fixtures/test_registry/packs/simple_docker/README.md
  fixtures/test_registry/packs/simple_docker/metadata.hcl
  fixtures/test_registry/packs/simple_docker/outputs.tpl
  fixtures/test_registry/packs/simple_docker/templates/_helpers.tpl
  fixtures/test_registry/packs/simple_docker/templates/simple_docker.nomad.tpl
  fixtures/test_registry/packs/simple_docker/variables.hcl
  go.mod
  internal/pkg/cache/cache.go
  internal/pkg/cache/cache_test.go
Labels: type/bug, theme/testing

#405 [actions] Disable caching for the golangci-lint action
  .github/workflows/golang-ci-lint.yml
Labels: theme/gh/actions

#416 [cli] Fixed default printing for string flags
  internal/pkg/flag/flag_var.go
  internal/pkg/flag/set.go
Labels: type/bug, theme/cli
